/*
 * Fixed-size sliding-window log-mel front-end for the SIH26172 voice activator.
 *
 * This is the C mirror of `ml/common/features.py`.  It is deliberately written
 * in portable C99 (no dynamic allocation, no libm beyond logf/cosf at init) so
 * that the *same* code runs in three places:
 *
 *   1. on the ESP32-S3 firmware,
 *   2. in the host simulator (edge/host_sim), where it is diffed against the
 *      Python reference by tests/test_frontend_parity.py, and
 *   3. in the ASR server's documentation examples.
 *
 * Memory: one sample ring of (frame_length + 2*hop) samples plus one 49x40
 * int8 feature window.  Nothing else is allocated at run time.
 *
 * Copyright: submission for Smart India Hackathon 2026 (ISRO, SIH26172).
 */
#ifndef KWS_FRONTEND_H
#define KWS_FRONTEND_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "kws_frontend_tables.h" /* generated by edge/tools/export_frontend_header.py */

#ifdef __cplusplus
extern "C" {
#endif

/* ---- geometry (must match ml/common/features.py) ----------------------- */
#define KWS_SAMPLE_RATE 16000
#define KWS_FRAME_LENGTH 480 /* 30 ms */
#define KWS_FRAME_HOP 320    /* 20 ms */
#define KWS_FFT_SIZE 512
#define KWS_NUM_MEL_BINS 40
#define KWS_CONTEXT_FRAMES 49
#define KWS_WINDOW_SAMPLES (KWS_FRAME_HOP * (KWS_CONTEXT_FRAMES - 1) + KWS_FRAME_LENGTH) /* 15840 == 0.99 s */

typedef struct {
    float scale;    /* affine int8 quantisation scale       */
    int32_t zero_point;
    float log_floor; /* minimum power before log()           */
} kws_quant_t;

typedef struct {
    /* input side: raw 16-bit PCM ring of the last `hop` samples */
    int16_t sample_ring[KWS_FRAME_HOP];
    uint32_t samples_since_frame;

    /* rolling spectrogram: KWS_CONTEXT_FRAMES x KWS_NUM_MEL_BINS, int8 */
    int8_t frames[KWS_CONTEXT_FRAMES][KWS_NUM_MEL_BINS];
    uint32_t frames_filled;

    /* scratch */
    float fft_re[KWS_FFT_SIZE];
    float fft_im[KWS_FFT_SIZE];
    uint32_t bit_reverse[KWS_FFT_SIZE];

    kws_quant_t quant;
    uint32_t frames_emitted;
} kws_frontend_t;

/*
 * Initialise the front-end.  Precomputes the bit-reversal table.  The Hann
 * window and mel filterbank come from the generated tables header so they are
 * bit-identical to the values used in training.
 */
void kws_frontend_init(kws_frontend_t *fe, kws_quant_t quant);

/*
 * Compute the log-mel vector for one frame of KWS_FRAME_LENGTH samples.
 * `frame` must point at KWS_FRAME_LENGTH int16 samples.
 */
void kws_frontend_frame(const kws_frontend_t *fe, const int16_t *frame, int8_t out[KWS_NUM_MEL_BINS]);

/*
 * Push `n` new samples into the streaming front-end.
 *
 * Returns true when at least one new analysis frame was produced (i.e. a new
 * window is ready to be scored).  This is the function the firmware calls from
 * its I2S/DMA callback: it never allocates and its cost is bounded.
 */
bool kws_frontend_push(kws_frontend_t *fe, const int16_t *samples, size_t n);

/*
 * Copy the current 49x40 int8 window into `out` (row-major,
 * KWS_CONTEXT_FRAMES * KWS_NUM_MEL_BINS bytes).  Before 49 frames exist the
 * window is left-padded with the quantised floor value, exactly like training.
 */
void kws_frontend_window(const kws_frontend_t *fe, int8_t *out);

/* Number of analysis frames produced since init (== windows available). */
uint32_t kws_frontend_frames(const kws_frontend_t *fe);

/* Reset the streaming state (keeps the precomputed tables). */
void kws_frontend_reset(kws_frontend_t *fe);

/*
 * Convenience one-shot helper used by the host simulator and unit tests:
 * waveform -> (KWS_CONTEXT_FRAMES * KWS_NUM_MEL_BINS) int8 features, using the
 * same left-padding rule as the streaming path.
 */
void kws_frontend_waveform_to_features(const int16_t *pcm, size_t n_samples, int8_t *out_features);

#ifdef __cplusplus
}
#endif

#endif /* KWS_FRONTEND_H */
